version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zk
    network_mode: host
    environment:
      ZOO_ADMINSERVER_ENABLED: 'false'
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
